version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Adjust the Python version if necessary
    commands:
      - echo "Installing AWS CLI"
  pre_build:
    commands:
      - echo "Preparing the environment"
      - pip install --upgrade awscli
  build:
    commands:
      - echo "Zipping the Lambda function code"
      - zip function.zip lambda_function.py
  post_build:
    commands:
      - echo "Deploying the Lambda function"
      - aws lambda update-function-code \
          --CICD-Test-Function-1 YourLambdaFunctionName \
          --zip-file fileb://function1.zip

artifacts:
  type: zip
  paths:
    - '*'
